#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: punchnat
# REQUIRE: LOGIN DAEMON
# KEYWORD: shutdown

# Add these lines to /etc/rc.conf.local or /etc/rc.conf to enable `punchnatd':
#
# punchnatd_enable (bool):          Set to "NO" by default.
#                                   Set it to "YES" to enable punchnatd
# punchnatd_config (path):          Set to "/usr/local/etc/punchnatd/config.conf" by default
#                                   Set it to the punchnatd server config

. /etc/rc.subr

name="punchnatd"
rcvar="${name}_enable"

eval ": \${${name}_enable:=\"NO\"}"
eval ": \${${name}_config:=\"/usr/local/etc/${name}/config.conf\"}"

pidfile="/var/run/${name}.pid"
procname="/usr/local/bin/punchnat"
configfile="$(eval echo \${${name}_config})"

start_precmd="punchnatd_startprecmd"
start_cmd=punchnatd_start

punchnatd_startprecmd()
{
	touch "${pidfile}"
}

punchnatd_start()
{
	/usr/sbin/daemon -c -p ${pidfile} ${procname} ${configfile} > /dev/null 2>&1
}

load_rc_config "$name"
run_rc_command "$1"
